apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: microservices-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: ms.example.com
    http:
      paths:
      # Paths will be appended by the build-ingress.sh script
