apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-base-hello-world
  labels:
    app: nginx-base
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-base
  template:
    metadata:
      labels:
        app: nginx-base
    spec:
      containers:
        - name: nginx-base-image
          image: gcr.io/grauj-gcp/nginx-static:v0
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-base-service
spec:
  selector:
    app: nginx-base
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
